apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-rs
spec:
  minReadySeconds: 30
  replicas: 2
  selector:
    matchLabels:
      app: webapp # it should be same as the label of POD
  template:
    metadata:
      labels:
        app: webapp # label key app can be any other name
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0
