apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp # label key app can be any other name
    release: "0" # introduce new label
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-release-0-5
  labels:
    app: webapp # label key app can be any other name
    release:  "0-5"
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: v1
kind: Pod
metadata:
  name: activemq
  labels:
    app: activemq # label key app can be any other name
spec:
  containers:
  - name: activemq
    image: richardchesterwood/k8s-fleetman-webapp-angular:release1