apiVersion: v1
kind: Service
metadata:
  name: activemq-service
spec:
# this defines which pods are going to be represented by this service.
# The service becomes a network endpoint for either other services or may be external
# users to connect to (browser)
  selector:
    app: queue # it should be same as the label of POD
  ports:
  - name: http
    port: 8161
    nodePort: 30010 # node port should be in the range 30000 to 32767

  - name: endpoint
    port: 61616

  type: NodePort