apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
# this defines which pods are going to be represented by this service.
# The service becomes a network endpoint for either other services or may be external
# users to connect to (browser)
  selector:
    app: webapp # it should be same as the label of POD
  ports:
  - name: http
    port: 80
    nodePort: 30080 # node port should be in the range 30000 to 32767
  type: NodePort

