apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  #minReadySeconds: 30
  replicas: 1
  selector:
    matchLabels:
      app: queue # it should be same as the label of POD
  template:
    metadata:
      labels:
        app: queue # label key app can be any other name
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release1
