apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  #minReadySeconds: 30
  replicas: 1
  selector:
    matchLabels:
      app: queue # it should be same as the label of POD
  template:
    metadata:
      labels:
        app: queue # label key app can be any other name
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release1


---

apiVersion: v1
kind: Service
metadata:
  name: activemq-service
spec:
# this defines which pods are going to be represented by this service.
# The service becomes a network endpoint for either other services or may be external
# users to connect to (browser)
  selector:
    app: activemq # it should be same as the label of POD
  ports:
  - name: http
    port: 8161
    nodePort: 30010 # node port should be in the range 30000 to 32767
  type: NodePort